### ISSUE TITLE
AddMissingDirectoryIfNeeded

### ISSUE THREAD

**Issue by inpas-test** [kevincolyar/tfs2svn#5]
Hi, Should not be so: RunSvnCommand("add --force \"" + path + "\""); instead RunSvnCommand("add --force \"" + this._workingCopyPath + "\""); ?

**Comment by kevincolyar** [comment]
Please submit a pull request if you feel like you have a contribution.

**Comment by inpas-test** [comment]
Sory, My mistake: Should not be so: RunSvnCommand("add --force \"" + directory+ "\""); ?
